### ISSUE TITLE
Connection fails on rM1 fw 2.10.0.324 rmioc::input error

### ISSUE THREAD

**Issue by mm-dev-rocks** [matteodelabre/rmvncclient#34]
On rM1 with latest firmware 2.10.0.324

VNSee 0.4.0-2 installed via toltec

I can launch the GUI but when I try to connect I get:
`Error: (rmioc::input) Get axis state: Invalid argument`

Seems similar to the issue reported/fixed here for fw 2.9:
https://github.com/matteodelabre/vnsee/issues/28

**Comment by matteodelabre** [comment]
Hi! As stated in the issue you linked, you need to install VNSee 0.4.1 to fix this issue. The package version in Toltec is not yet up to date (waiting on approval for PR toltec-dev/toltec#421). In the meantime, please manually install the latest version.

**Comment by mm-dev-rocks** [comment]
I did see that but there was a recent comment from someone on 0.4.1 who was still getting the error so I thought it wasn't fixed

https://github.com/matteodelabre/vnsee/issues/28#issuecomment-927503945

I'll give it a try though, thanks

EDIT I've tried the 0.4.1 binary and it's working fine for me. Great thank you.

**Comment by matteodelabre** [comment]
Thanks for confirming it worked!
