### ISSUE TITLE
Incompability with streaming solutions

### ISSUE THREAD

**Issue by Utopiah** [matteodelabre/rmvncclient#36]
See https://github.com/rien/reStream/issues/84 and https://github.com/owulveryck/goMarkableStream/issues/23 , both solutions don't work until vnsee is killed.

**Comment by Utopiah** [comment]
Might be related to using vnsee without killing xochtil first. While testing running both and also a streaming solution, reStream, did work so maybe entered a strange context.

**Comment by Utopiah** [comment]
Happened again, `opkg remove vnsee` didn't fix it, even after  reboot, but somehow `./entware-reenable` did so I'm not sure what is going on here.

**Comment by matteodelabre** [comment]
@Utopiah Are you still encountering this bug? Could you share more on your exact setup?

**Comment by Utopiah** [comment]
I believed we had a chat on Discord about it. I can't recall exactly but I think my mistake was not killing xochtil first. If that's important for you I could try again and let you know. Otherwise feel free to close this issue for now. If need be I'd open another one, as you prefer.

**Comment by matteodelabre** [comment]
Forgot about that, sorry! Alright, closing this for now then.
