### ISSUE TITLE
Does VNC require wifi?

### ISSUE THREAD

**Issue by detrieo** [matteodelabre/rmvncclient#40]
Hi
I'm completely new to VNC.
If I use vnsee with cable, does it still require network? or is it through cable alone? 
Can this work like any external display?

**Comment by matteodelabre** [comment]
Hi @detrieo, yes you can setup VNSee to use your tablet as an external display with just an USB cable.

**Comment by detrieo** [comment]
So all it takes is proper linux setup, and connected remarkable? No need for wifi connection? while using vnsee rm can have wifi off? even flight mode?

**Comment by matteodelabre** [comment]
Right, exactly!
