### ISSUE TITLE
Cannot see mouse pointer

### ISSUE THREAD

**Issue by damienchallet** [matteodelabre/rmvncclient#5]
First, many thanks for your work. Would it be possible to show the mouse pointer in the vnc client ?

**Comment by matteodelabre** [comment]
Hi @damienchallet! If you’re following the instructions from the “README” file, can you try removing the `-nocursor` flag when invoking x11vnc? Otherwise, which VNC server are you using?

**Comment by damienchallet** [comment]
Yes, that works. Case closed, thanks !
