### ISSUE TITLE
Disabling gestures?

### ISSUE THREAD

**Issue by stevenbell** [matteodelabre/rmvncclient#8]
Is there a way to disable touch gestures?  I'm trying to use this in concert with a drawing program, and often find myself accidentally scrolling the page as I move my hand around.

**Comment by matteodelabre** [comment]
Thank you for your suggestion! I guess we could add a flag that disables touch gestures.

**Comment by matteodelabre** [comment]
@stevenbell I just added a flag called `--no-touch` that disables any interaction with the touch screen. Can you please tell me if that fits your use case? Thanks!

**Comment by stevenbell** [comment]
Works great, thanks!
I can still use the pen for tap/click, so this is perfect.
